networks:
  kbbi-scraper:

services:
  app:
    image: node:18
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm run dev
    working_dir: /app
    depends_on:
      - db
    networks:
      - kbbi-scraper

  db:
    image: mongo:4
    restart: unless-stopped
    expose: 
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    networks:
      - kbbi-scraper

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/
    depends_on:
      - db
    networks:
      - kbbi-scraper
