networks:
  kbbi-scraper:

services:
  app:
    image: node:18-alpine
    restart: unless-stopped
    volumes:
      - .:/app
    command: npm start
    working_dir: /app
    depends_on:
      - db
    networks:
      - kbbi-scraper
